[global]
  sendAnonymousUsage = false

[serversTransport]
  InsecureSkipVerify = true

[log]
  level = "INFO"
  format = "common"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
    swarmMode = false
  [providers.file]
    filename = "/etc/traefik/dyn.toml"

	
[accessLog]
  filePath = "/tmp/access.log"

[api]
  dashboard = false
  debug = false

[entryPoints]
  [entryPoints.secure]
    address = ":443"

