---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

subtitle: "ZVELK"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
columns: 5
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/V1D1AN/ZVELK"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://github.com/V1D1AN/ZVELK/wiki"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "OSINT"
    icon: "fas fa-fingerprint"
    items:
      - name: "Spiderfoot"
        logo: "/assets/icons/spiderfoot.png"
        tag: "app"
        url: "https://s1em_hostname/spiderfoot/"
        target: "_blank" # optional html a tag target attribute

  - name: "SIRP"
    icon: "fas fa-sitemap"
    items:
      - name: "Velociraptor"
        logo: "/assets/icons/velociraptor.png"
        tag: "app"
        url: "https://s1em_hostname/velociraptor/"
        target: "_blank" # optional html a tag target attribute
      - name: "Zircolite"
        logo: "/assets/icons/zircolite.png"
        tag: "app"
        url: "https://s1em_hostname/kibana/app/dashboards#/view/832a98e0-9ef0-11ed-bedc-f9813e7df557"
        target: "_blank" # optional html a tag target attribute

  - name: "TOOLS"
    icon: "fas fa-tools"
    items:
      - name: "CyberChef"
        logo: "/assets/icons/cyberchef.jpg"
        tag: "app"
        url: "https://s1em_hostname/cyberchef/"
        target: "_blank" # optional html a tag target attribute
      - name: "CodiMD"
        logo: "/assets/icons/codimd.jpg"
        tag: "app"
        url: "https://s1em_hostname/codimd/"
        target: "_blank" # optional html a tag target attribute
      - name: "StartMe"
        logo: "/assets/icons/startme.png"
        tag: "site"
        tagstyle: "is-success"
        url: "https://start.me/p/6r66da/cybersecurity"
        target: "_blank" # optional html a tag target attribute

  - name: "UPLOAD"
    icon: "fas fa-cloud-arrow-up"
    items:
      - name: "Zircolite"
        logo: "/assets/icons/evtx.png"
        tag: "app"
        url: "https://s1em_hostname/zircolite/"
        target: "_blank" # optional html a tag target attribute
      - name: "Velociraptor"
        logo: "/assets/icons/zip.png"
        tag: "app"
        url: "https://s1em_hostname/velociraptor-upload/"
        target: "_blank" # optional html a tag target attribute
